movie_reviews/main/routes.py
from flask import render_template, Blueprint, request, current_app, redirect, url_for
import os
from movie_reviews.models import Movie
from movie_reviews import db

main = Blueprint('main',__name__)
print('main')

data = [{'name': 'Leo', 'rating':8.5},{'name': 'Spiderman', 'rating':9.5}]

@main.route('/')
@main.route('/home')
def home():
    movies = Movie.query.order_by(Movie.rating.desc())
    return render_template('home.html', title='Home', movies=movies)

@main.route('/api')
def api():
    return data

movie_reviews/movies/routes.py
from flask import render_template, Blueprint, request, current_app, redirect, url_for,flash
import os
from movie_reviews.models import Movie, Review
from movie_reviews import db
from flask_login import current_user, login_required
from functools import wraps
import tensorflow as tf
import json
from tensorflow.keras.preprocessing.sequence import pad_sequences

print('movies')

KAFKA_PUBLISH = False

if KAFKA_PUBLISH:
    from movie_reviews.movies.kafka_publish import get_producer,publish
    producer = get_producer()

f = open('./movie_reviews/aimodel/tokenizer.json')
tokenizer = tf.keras.preprocessing.text.tokenizer_from_json(json.load(f))
f.close()

vocab_size = 10000
max_length = 120
embedding_dim = 16
trunc_type='post'
oov_tok = "<OOV>"

# Build the model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Setup the training parameters
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.load_weights('./movie_reviews/aimodel/modelcheckpoint/my_checkpoint')

movies = Blueprint('movies',__name__)


def admin_required():
    def wrapper(fn):
        @wraps(fn)
        def check_(*a,**k):
            if current_user is not None and current_user.is_admin:
                return fn(*a,**k)

            else:
                print("No Admin privileges")
                return redirect(url_for('main.home'))
    
        return check_
    return wrapper


@movies.route('/movie/new', methods=['GET','POST'])
@login_required
@admin_required()
def add_movie():
    if request.method=='POST':
        print('POST')
        print(request.form['title'])
        movie = Movie(title=request.form['title'], year=request.form['year'], description=request.form['description'])
        if request.files['poster']:
            poster = request.files['poster']
            poster.save(os.path.join(current_app.root_path,'static/posters/', poster.filename))
            movie.image = poster.filename
        db.session.add(movie)
        db.session.commit()
        return redirect(url_for('main.home'))

    return render_template('add_movie.html', title='Add movie', legend='Add Movie')

@movies.route('/movie/<int:movie_id>/', methods=['GET','POST'])
def movie(movie_id):
    movie = Movie.query.get_or_404(movie_id)
    if request.method=='POST':
        if current_user is not None:
            review = request.form['comment']
            test_seq = [review]
            test_seq = tokenizer.texts_to_sequences(test_seq)
            test_padded = pad_sequences(test_seq,maxlen=max_length, truncating=trunc_type)
            result = model.predict(test_padded)
            label= 'positive' if result[0][0]>=0.5 else 'negative'
            review = Review(content=review,label=label,movie=movie,review_score=result[0][0],author=current_user)
            movie.review_count+=1
            if review.review_score>=0.5:
                movie.positive_count+=1
            movie.rating = round(movie.positive_count/movie.review_count,2)
            db.session.add(review)
            db.session.add(movie)
            db.session.commit()
            if KAFKA_PUBLISH:
                publish(producer,movie,review,result[0][0])
            print(result)
        else:
            flash('User needs to login to add review', 'danger')
    reviews = Review.query.filter_by(movie=movie).order_by(Review.added_date.desc())
    return render_template('movie.html',movie=movie,title=movie.title,reviews=reviews)

@movies.route('/review/<int:review_id>/delete')
@login_required
def delete_review(review_id):
    print(review_id)
    review = Review.query.get_or_404(review_id)
    if review.author!=current_user:
        flash("User doesn't have permission to delete the review!", 'danger')
        return redirect(url_for('main.home'))
    
    movie = review.movie
    if review.label=='positive':
        movie.positive_count-=1
    movie.review_count-=1
    if movie.review_count!=0:
        movie.rating = round(movie.positive_count/movie.review_count,2)
    else:
        movie.rating = 0
    db.session.delete(review)
    db.session.commit()
    return redirect(url_for('movies.movie', movie_id=movie.id))


movie_reviews/users/routes.py
from flask import render_template, Blueprint, request, current_app, redirect, url_for,flash
from movie_reviews.models import User
from movie_reviews import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users',__name__)
print('users')

def validate(request):
    valid = True
    user = User.query.filter_by(username=request.form['username']).first()
    if user is not None:
        valid=False
        flash('Username already exists. Registration failed', 'danger')
    user = User.query.filter_by(email=request.form['email']).first()
    if user is not None:
        valid=False
        flash('Email already exists. Registration failed', 'danger')
    password1 = request.form['password1']
    password2=request.form['password2']
    if password1!=password2:
        valid=False
        flash("Passwords don't match",'danger')
    return valid
    


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    if request.method == 'POST':
        if validate(request):
            password_hash = bcrypt.generate_password_hash(request.form['password1']).decode('utf-8')
            user = User(username=request.form['username'],password=password_hash,email=request.form['email'])
            db.session.add(user)
            db.session.commit()
            flash('User registration successfull', 'success')
            login_user(user)
            next = request.args.get('next')
            return redirect(next) if next else redirect(url_for('main.home'))
        

    return render_template('register.html', title='Register')


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    if request.method == 'POST':
        user = User.query.filter_by(username=request.form['username']).first()
        if user and bcrypt.check_password_hash(user.password, request.form['password']):
            login_user(user)
            next = request.args.get('next')
            return redirect(next) if next else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')

    return render_template('login.html', title='Login')

    
@users.route('/logout')
def logout():
    logout_user()
    next = request.args.get('next')
    return redirect(next) if next else redirect(url_for('main.home'))
    # return redirect(url_for('main.home'))

movie_reviews/templates/add_movie.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    <form action="" method="post" enctype="multipart/form-data">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                {{ legend }}
            </legend>
            <div class="form-group">
                <label for="title" class="form-control-label">Title</label> 
                <input type="text" class="form-control form-control-lg" name="title" required>
            </div>
            <div class="form-group">
                <label for="year" class="form-control-label">Year</label> 
                <input type="text" class="form-control form-control-lg" name="year" required>
            </div>
            <div class="form-group">
                <label for="poster" class="form-control-label">Poster</label> 
                <input class="form-control-file" id="poster" name="poster" type="file">
            </div>
            <div class="form-group">
                <label for="description" class="form-control-label">Description</label> 
                <textarea class="form-control form-control-lg" id="description" name="description"></textarea> 
            </div>
            
        </fieldset>
        <div class="form-group">
            <input type="submit" value="Add" class="btn btn-primary">        
        </div>
    </form>
</div>

{% endblock content%}

movie_reviews/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <hr>
    {% for movie in movies %} 
     <div class="media movie-item">
      <a href="{{url_for('movies.movie', movie_id=movie.id)}}">
        <img class="mr-3 title-img" src="{{url_for('static', filename='posters/'+movie.image)}}" alt="Generic placeholder image">
        <div class="media-body">
          <h4 class="mt-0">{{movie.title}}</h4></a>
          <h6 class="mt-0">Year: {{movie.year}}</h6>
          <p>
            {% if movie.review_count>0 %}
            Rating: <b> {{movie.rating*10}}</b>({{movie.review_count}})
            {% else %}
            Not Rated
            {% endif %}
          </p>
          
        </div>
      </div>
    
    <hr>
    {% endfor %}

{% endblock content%}

movie_reviews/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css')}}"> 
    {% if title %}
    <title>Movie Reviews - {{title}}</title>
    {% else %} 
    <title>Movie Reviews</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Movie Reviews</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                <a class="nav-item nav-link" href="">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                {% if current_user.is_admin %}
                <a class="nav-item nav-link" href="{{url_for('movies.add_movie')}}">Add movie</a>
                {% endif %}
                <a class="nav-item nav-link" href="#"><b>{{current_user.username}}</b></a>
                <a class="nav-item nav-link" href="{{url_for('users.logout', next=request.path)}}">Logout</a>
                {% else %} 
                <a class="nav-item nav-link" href="{{url_for('users.register', next=request.path)}}">Register</a>
                <a class="nav-item nav-link" href="{{url_for('users.login', next=request.path)}}">Login</a>
                {% endif %}  
               
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
             {% for category,message in messages %}
             <div class="alert alert-{{category}}">
                {{message}}
             </div> 
             {% endfor %}  
            {% endif %} 
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <!-- <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div> -->
        </div>
      </main>
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

movie_reviews/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Log In
                </legend>
                <div class="form-group">
                   <label for="username" class="form-control-label">Username</label> 
                   <input type="text" class="form-control form-control-lg" name="username" required>
                </div>
                <div class="form-group">
                    <label for="password" class="form-control-label">Password</label> 
                   <input type="password" class="form-control form-control-lg" name="password" required>
                </div>
            </fieldset>
            <div class="form-group">
                <input type="submit" class="btn btn-outline-info">
                
            </div>
            
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Do not Have An Account? <a class="ml-2" href="{{url_for('users.register')}}">Sign Up</a>
        </small>
    </div>
    
{% endblock content %}

movie_reviews/templates/movie.html
{% extends "layout.html" %}
{% block content %}

    
    <div class="media movie-item">
        <img class="mr-3 title-img" src="{{url_for('static', filename='posters/'+movie.image)}}" alt="Generic placeholder image">
        <div class="media-body">
          <h4 class="mt-0">{{movie.title}}</h4>
          <h6 class="mt-0">Year: {{movie.year}}</h6>
          <p>{% if movie.review_count>0 %}
            Rating: <b> {{movie.rating*10}}</b>({{movie.review_count}})
            {% else %}
            Not Rated
            {% endif %}
          </p>

          <!-- <p>{{request.path}}</p> -->
          
        </div>
      </div>
      {% if current_user.is_authenticated %}
      <form action="" method="post">
        <fieldset class="form-group">
          <div class="form-group">
            <label for="description" class="form-control-label">Comment: </label> 
            <textarea class="form-control form-control-lg" id="comment" name="comment" required></textarea> 
        </div>
        
    </fieldset>
    <div class="form-group">
      <input type="submit" value="Submit" class="btn btn-primary">        
    </div>
    </form>
    {% else %}
    Log In to add review. 
    <a href="{{ url_for('users.login', next=request.path) }}">Login</a>
    <br>
    <br>
    {% endif %}


      {% if reviews %}
      <h5>Reviews: </h5>
      {% for review in reviews %}
      <p>
        <b>{{review.author.username}}: </b> 
        {% if review.label=='positive' %}
        <span class="badge badge-success">{{review.label}}</span>
        {% else %}
        <span class="badge badge-danger">{{review.label}}</span>
        {% endif %}
        {% if review.author==current_user %}
        <a href="{{ url_for('movies.delete_review', review_id=review.id)}}"> <svg  xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
          <path title="Delete" d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
        </svg></a>
        {% endif %}
        <br>
        {{ review.content }}
        <br>
        
        <!-- <br> -->
        

      </p>
      {% endfor %}
      {% else %}
      {% endif %}

      
{% endblock content%}

movie_reviews/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Join Today
                </legend>
                <div class="form-group">
                    <label for="username" class="form-control-label">Username</label> 
                    <input type="text" class="form-control form-control-lg" name="username" required>
                 </div>
                 <div class="form-group">
                    <label for="email" class="form-control-label">Email</label> 
                    <input type="email" class="form-control form-control-lg" name="email" required>
                 </div>
                 <div class="form-group">
                    <label for="password1" class="form-control-label">Password</label> 
                   <input type="password" class="form-control form-control-lg" name="password1" required>
                </div>
                <div class="form-group">
                    <label for="password2" class="form-control-label">Confirm Password</label> 
                   <input type="password" class="form-control form-control-lg" name="password2" required>
                </div>
                
            </fieldset>
            <div class="form-group">
                <input type="submit" class="btn btn-outline-info">
                
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{url_for('users.login')}}">Sign In</a>
        </small>
    </div>
{% endblock content %}